# Учетные данные
username: "Super Allex"
password: "..."

# Настройки бота
base_url: "https://nebo.mobi"
timeout: 30

# Настройки имитации человека
delay_min: 1
delay_max: 3

# Настройки логирования
log_level: "INFO"
log_file: "nebo_bot.log"